<?php
 include "connection.php";
 session_start();
 include "custSidebar.php";
 $id = $_GET['id'];
 $sqlx = "SELECT * from tbl_bookshows where id= $id and status=1";
 $resultx = mysqli_query($conn, $sqlx);
 $rowx = mysqli_fetch_assoc($resultx);
 $sid = $rowx['schid'];
 $sql = "SELECT * from tbl_schedule where id= $sid";
 $result = mysqli_query($conn, $sql);
 $row = mysqli_fetch_assoc($result);
?>

<?php
$apiKey="rzp_test_3C3CGx9HOoWYRI";
?>

<div class="center">
    <center><h3>BOOKING SUMMARY</h3></center>
    <table>
    <tr>
        <td>Date</td>
        <td><?php echo $row['date'];?></td>
    </tr>
    <tr>
        <td>Expected Time</td>
        <td><?php echo $row['time_from'];?> - <?php echo $row['time_to'];?></td>
    </tr>
    <tr>
        <td>Hours</td>
        <td><?php echo $rowx['hours'];?></td>
    </tr>
    <tr>
        <td>Rate</td>
        <td><?php echo $rowx['show_cost'];?></td>
    </tr>
    </table>
    <center>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $rowx['show_cost']*100 ;?>"  // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="order_CgmcjRh9ti2lP7"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Fragrance IND"
    data-description="Everything’s better with a bit of fragrance."
    data-image="https://st4.depositphotos.com/31445094/41249/v/1600/depositphotos_412499652-stock-illustration-perfume-icon-design-template-isolated.jpg"
    data-prefill.name="Minu Joe"
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden" class="btn btn-primary">
</form>
If you have already paid <a href="artst_customer_view.php">click here</a>
</center>
<!--gateway end-->
</div>
<style>
    .razorpay-payment-button{
        background-color: #0DCAF0;
        color: white;
        font-size: 18px;padding: 8px 10px;font-weight: bold;
        border-radius: 12px; border: none;text-align: center; 
    }

    .center {
        position: absolute;
        top: 50%;
        left: 60%;
        transform: translate(-50%, -50%);
        border:3px solid black;
        padding:20px;
        }
        td{
            padding:10px;
        }
</style>